name: Engine CI

on:
  push:
    branches: ['main']
    paths:
      - 'apps/engine/**'
  pull_request:
    branches: ['main']
    paths:
      - 'apps/engine/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      - name: Install Rust target for Soroban
        run: |
          source $HOME/.cargo/env
          rustup target add wasm32v1-none
      - name: Install Stellar CLI with Homebrew
        run: |
          brew update
          brew install stellar-cli
          stellar --version
      - name: Build Cargo project
        run: |
          source $HOME/.cargo/env
          cargo build --verbose
        working-directory: apps/engine

      - name: Check formatting cargo
        run: |
          cargo fmt -- --check
        working-directory: apps/engine
    
      - name: Build wasm32
        run: |
          cargo build --target wasm32-unknown-unknown --release
        working-directory: apps/engine

      - name: Build Stellar contract
        run: |
          source $HOME/.cargo/env
          stellar contract build --verbose
        working-directory: apps/engine

      - name: Run Cargo tests
        run: |
          source $HOME/.cargo/env
          cargo test --verbose
        working-directory: apps/engine
